/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./src/**/*.{js,jsx,ts,tsx}"],
    theme: {
        fontFamily: {
            Exo: ["exo"],
        },
        screens: {
            mb: "320px",
            mbx: "427px",
            tl: "767px",
            lt: "1023px",
            dt: "1279px",
        },
        boxShadow: {
            Shadow: " 0px 10px 6px -1px rgba(0,0,0,0.2);",
            whiteShadow: "0px 14px 6px 0px rgba(255,255,255,0.18);",
        },
        backgroundColor: {
            bgButton: "#118273",
            premierColor: "#00544a",
            bgOverlay: "rgba(0, 0, 0, 0.5)",
        },
        extend: {
            preload: {
                none: "none",
                metadata: "metadata",
                auto: "auto",
            },
            fontSize: {
                13: "13px",
                14: "14px",
                16: "16px",
                20: "20px",
                24: "24px",
                26: "26px",
                32: "32px",
                32: "32px",
                48: "48px",
            },
        },
        gridTemplateRows: {
            1: "repeat(1, minmax(0, 1fr))",
            2: "repeat(2, minmax(0, 1fr))",
            3: "repeat(3, minmax(0, 1fr))",
            4: "repeat(4, minmax(0, 1fr))",
            5: "repeat(5, minmax(0, 1fr))",
            6: "repeat(6, minmax(0, 1fr))",
            7: "repeat(7, minmax(0, 1fr))",
            8: "repeat(8, minmax(0, 1fr))",
            9: "repeat(9, minmax(0, 1fr))",
            10: "repeat(10, minmax(0, 1fr))",
            11: "repeat(11, minmax(0, 1fr))",
            12: "repeat(12, minmax(0, 1fr))",
            13: "repeat(13, minmax(0, 1fr))",
            14: "repeat(14, minmax(0, 1fr))",
        },
        gridRowStart: {
            1: "1",
            2: "2",
            3: "3",
            4: "4",
            5: "5",
            6: "6",
            7: "7",
            8: "8",
            9: "9",
            10: "10",
            11: "11",
            12: "12",
            13: "13",
            14: "14",
        },
        gridRowEnd: {
            1: "1",
            2: "2",
            3: "3",
            4: "4",
            5: "5",
            6: "6",
            7: "7",
            8: "8",
            9: "9",
            10: "10",
            11: "11",
            12: "12",
            13: "13",
        },

        backgroundImage: {
            "background-footer": "url('/src/components/assets/FOOTER.jpg')",
        },
    },
    variants: {
        extend: {
            preload: ["responsive"],
        },
    },
    plugins: [],
};
